language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
- dotnet restore
script:
- dotnet build
- dotnet publish
before_deploy:
- cd ${TRAVIS_BUILD_DIR}/bin/Debug/netstandard2.1/publish
- zip -qr BlazorDiceGame.zip .
deploy:
  provider: releases
  api_key:
    secure: bGLvd/aw5j0Llf5Tz4WWRFJqLXifwmIYbOQUdindmGKjgaIsIj9EHuOix0767lA0QujIEI031snxgOO44A19Sl7ce5N+8rj+5pjWTrKKmf/IHHoBr/qvlBUega5OYDiuwo1TP2UiSeaqSBhLpeCIRwcYXiF6mQ0tXboLC1uWklTFFll4aCSGGSSV+CRBdN4IrsRyvnvVFt+7Nm7RZTZQePbJkAxHJBWrFJxgFJLKEIV3g/Xp4UyN1pVmdVuCRqQpFgH+oyE0hx1FwYnBJDS4YxDrimIFcD9mluTznZqtEUYKL6zLUVprpzcwH8RWPwb29UIU2g5d9iqdaQiE2BUDPjuSc/LsLMckS9trFYVB1raGzBgwqqG0leI8Za2RSL/krqI6TLD6YI0MrDIx+tCYPAArVFY7bXxg9igV0+WalnW5w+uVL7DUSNbf+DB903vx0Q6lOEDswXwCUSz8Nt4ITgzKXH46nDXam5g65y5y6nHbrwnTEYNenKsv2JkPQiMNabfwMn+yvIe51btsl86Y5J8VfUQbxi1oQZgPRBO8AuZop9yHzD3bucNTJHE03zKTv00YwaTbndCm456IsVnAQyviT8bXkIxjxxeEIq1xRy2iDzvKNHWFu7ZvwQsZI3jf6TbzMzuhvLaPNg8x5XMnVJWTGLjUVinWlF8j1gqf+ck=
  file: ${TRAVIS_BUILD_DIR}/bin/Debug/netstandard2.1/BlazorDiceGame.zip
  on:
    repo: DanielHWe/BlazorDiceGame
    all_branches: true
    tags: true
  skip_cleanup: 'true'
